### ISSUE TITLE
Getting cate not found error when running main.py

### ISSUE THREAD

**Issue by PrudhviRaj12** [yzhan238/SeedTopicMine#2]
Hi, I am trying to run main.py with the same params on the yelp dataset, and I am getting this error on the os.system(cate_c)
sh: 1: ./cate/cate: not found 32512
And it is throwing this assertion error 

assert os.system(cate_c) == 0, "cate c command execute failed"
AssertionError: cate c command execute failed

**Comment by yzhan238** [comment]
Hi @PrudhviRaj12,

Thanks for your interests in our work! You should compile cate before your first run by typing `make` in the `./cate/` directory.

We will make it clearer.

**Comment by yzhan238** [comment]
Hi @PrudhviRaj12,

Thanks for your interests in our work! You should compile CatE before your first run by typing `make` in the `./cate/` directory. We will clarify this in the readme file.

**Comment by PrudhviRaj12** [comment]
Thank you sir, that worked! I love your work btw. It is unique and such a good way to tackle topic modeling.
